name: Create Pull Request to Develop

on:
  push:
    branches:
      - "feature/**"
      - "feature-*"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          base: develop
          title: "Automated Pull Request from ${{ github.head_ref }}"
          body: |
            This is an automated pull request to merge changes from ${{ github.head_ref }} to develop.
            Write your contribution message here, please.
          milestone: 1
          draft: false
