name: Create Pull Request to Develop

on:
  push:
    branches:
      - "feature/**"
      - "feature-*"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Branch Name
        id: get_branch
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.get_branch.outputs.branch_name }}
          base: develop
          title: "Automated Pull Request from ${{ steps.get_branch.outputs.branch_name }}"
          body: |
            This is an automated pull request to merge changes from ${{ steps.get_branch.outputs.branch_name }} to develop.
            Write your contribution message here, please.
          milestone: 1
          draft: false
