name: Release Creation Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - develop  # Aciona o workflow quando um PR para develop é fechado

jobs:
  create_release:
    if: github.event.pull_request.merged == true  # Apenas continua se o PR foi mergeado
    runs-on: ubuntu-latest

    steps:
      # Checkout the develop branch
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0  # Garante que todas as tags sejam baixadas

      # Get the latest tag
      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "v0.0.0")
          clean_tag=${latest_tag#v}  # Remove o prefixo 'v' da tag
          echo "LATEST_TAG=$clean_tag" >> $GITHUB_ENV

      # Get the label from the merged PR
      - name: Get PR Label
        id: get_label
        run: |
          label=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          echo "PR_LABEL=$label" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Calculate the next version based on the label and check if tag exists
      - name: Calculate Next Version
        id: calculate_version
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.LATEST_TAG }}"
          
          if [[ "${{ env.PR_LABEL }}" == "patch" ]]; then
            next_patch=$((patch + 1))
          elif [[ "${{ env.PR_LABEL }}" == "minor" ]]; then
            next_minor=$((minor + 1))
            next_patch=0  # Reset o patch ao incrementar o minor
          elif [[ "${{ env.PR_LABEL }}" == "major" ]]; then
            next_major=$((major + 1))
            next_minor=0  # Reset o minor
            next_patch=0  # Reset o patch ao incrementar o major
          fi
          
          next_version="$next_major.$next_minor.$next_patch"

          # Se a tag já existir, incrementa de novo
          while git rev-parse "v$next_version" >/dev/null 2>&1; do
            echo "Tag v$next_version already exists, incrementing again..."
            
            # Incrementa com base no tipo de release
            if [[ "${{ env.PR_LABEL }}" == "patch" ]]; then
              next_patch=$((next_patch + 1))
            elif [[ "${{ env.PR_LABEL }}" == "minor" ]]; then
              next_minor=$((next_minor + 1))
              next_patch=0
            elif [[ "${{ env.PR_LABEL }}" == "major" ]]; then
              next_major=$((next_major + 1))
              next_minor=0
              next_patch=0
            fi
            
            next_version="$next_major.$next_minor.$next_patch"
          done
          
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      # Check if the release branch exists
      - name: Check if release branch exists
        id: check_branch
        run: |
          branch_exists=$(git ls-remote --heads origin release-v${{ env.NEXT_VERSION }})
          if [[ -z "$branch_exists" ]]; then
            echo "Branch release-v${{ env.NEXT_VERSION }} does not exist, creating."
            echo "create_release_branch=true" >> $GITHUB_ENV
          else
            echo "Branch release-v${{ env.NEXT_VERSION }} already exists."
            echo "create_release_branch=false" >> $GITHUB_ENV
          fi

      # Create a new release branch and tag if it doesn't exist
      - name: Create Release Branch and Tag
        if: env.create_release_branch == 'true'
        run: |
          git checkout main
          git checkout -b release-v${{ env.NEXT_VERSION }}
          git push origin release-v${{ env.NEXT_VERSION }}
          gh release create "v${{ env.NEXT_VERSION }}" --title "Release v${{ env.NEXT_VERSION }}" --notes "Automatic release based on merged PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create Pull Request from develop to release
      - name: Create Pull Request from develop to release
        run: |
          gh pr create \
            --head develop \
            --base release-v${{ env.NEXT_VERSION }} \
            --title "Merge Develop into Release v${{ env.NEXT_VERSION }}" \
            --body "This PR merges the develop branch into release-v${{ env.NEXT_VERSION }}." \
            --label "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
