name: Release Creation Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - develop  # Aciona o workflow quando um PR para develop é fechado

jobs:
  create_release:
    if: github.event.pull_request.merged == true  # Somente continua se o PR foi mergeado
    runs-on: ubuntu-latest

    steps:
      # Checkout the develop branch, with all tags
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0  # Garante que todas as tags sejam baixadas

      # Get the latest tag
      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "v0.0.0")
          clean_tag=${latest_tag#v}  # Remove o prefixo 'v' da tag
          echo "LATEST_TAG=$clean_tag" >> $GITHUB_ENV

      # Get the label from the merged PR
      - name: Get PR Label
        id: get_label
        run: |
          label=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          echo "PR_LABEL=$label" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Calculate the next version based on the label
      - name: Calculate Next Version
        id: calculate_version
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.LATEST_TAG }}"
          if [[ "${{ env.PR_LABEL }}" == "patch" ]]; then
            next_patch=$((patch + 1))
            next_version="$major.$minor.$next_patch"
          elif [[ "${{ env.PR_LABEL }}" == "minor" ]]; then
            next_minor=$((minor + 1))
            next_version="$major.$next_minor.0"
          elif [[ "${{ env.PR_LABEL }}" == "major" ]]; then
            next_major=$((major + 1))
            next_version="$next_major.0.0"
          fi
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      # Check if the release already exists
      - name: Check if release already exists
        id: check_release
        run: |
          release_exists=$(gh release list --json tagName --jq '.[] | select(.tagName=="v'${{ env.NEXT_VERSION }}'")')
          if [[ -z "$release_exists" ]]; then
            echo "create_release=true" >> $GITHUB_ENV
          else
            echo "Release already exists, skipping creation." 
            echo "create_release=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create or update the release if it doesn't already exist
      - name: Create or Update Release
        if: env.create_release == 'true'  # Só cria a release se não existir
        run: |
          gh release create "v${{ env.NEXT_VERSION }}" --title "Release v${{ env.NEXT_VERSION }}" --notes "Automatic release based on merged PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Check for an existing PR from develop to release
      - name: Check for existing PR from develop to release
        id: check_pr
        run: |
          pr_exists=$(gh pr list --base release-v${{ env.NEXT_VERSION }} --head develop --state open --json number --jq '.[0].number')
          if [[ -z "$pr_exists" ]]; then
            echo "No PR found. Creating a new one."
            echo "create_pr=true" >> $GITHUB_ENV
          else
            echo "PR already exists: #$pr_exists"
            echo "create_pr=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create PR if no existing PR is found
      - name: Create Pull Request from develop to release
        if: env.create_pr == 'true'
        run: |
          gh pr create \
            --head develop \
            --base release-v${{ env.NEXT_VERSION }} \
            --title "Merge Develop into Release v${{ env.NEXT_VERSION }}" \
            --body "This PR merges the develop branch into release-v${{ env.NEXT_VERSION }}." \
            --label "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
