name: Automated Release Creation

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  create-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Garante que todas as tags e o histórico completo sejam baixados

      - name: Get Latest Tag
        id: get_tag
        run: |
          # Obtém a última tag pela data de criação
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Debug Latest Tag
        run: |
          echo "Usando a tag mais recente: ${{ env.LATEST_TAG }}"

      - name: Create Release Branch from Main
        run: |
          # Certifique-se de que estamos na branch main
          git switch main
          git pull origin main  # Puxa as últimas mudanças de main
          
          # Cria uma nova branch de release usando a tag mais recente
          git checkout -b release-${{ env.LATEST_TAG }}
          
          # Sobe a nova branch para o repositório
          git push --set-upstream origin release-${{ env.LATEST_TAG }}

      - name: Create Pull Request from Develop to Release
        run: |
          # Usar a GitHub CLI para criar o PR de develop para a nova release
          gh pr create --title "Merge Develop into Release ${{ env.LATEST_TAG }}" --base release-${{ env.LATEST_TAG }} --head develop --body "Automated PR to merge develop into release-${{ env.LATEST_TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
